$attention = rgb(fb6a6a)

general {
  col.active_border = rgb(f2fcff)
  col.inactive_border = rgba(30486099)
}

group {
    col.border_active = rgb(f2fcff)
    col.border_inactive = rgba(30486099)
}

decoration:shadow {
  range = 16
  render_power = 4
  color = rgb(6fb8e3)
  color_inactive = rgba(30486077)
}
